name: Update coros data

on:
  workflow_dispatch:
  schedule:
    - cron: "5 13,15 * * *"

jobs:
  build:
    name: Update-coros-data
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.COROS_EMAIL }}
      PASSWORD: ${{ secrets.COROS_PASSWORD }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - uses: actions/checkout@v2
        with:
          repository: summerscar/coros-box
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coros-box

      - run: |
          cd coros-box
          pnpm i
          pnpm start
          cd ../
          rm -rf ./coros-box

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":memo: update profile"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: Author <actions@github.com>
