name: Update coros data

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Manual triggers'
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 13,15 * * *"

jobs:
  build:
    name: Update-coros-data
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.COROS_EMAIL }}
      PASSWORD: ${{ secrets.COROS_PASSWORD }}
      
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
        with:
          repository: summerscar/coros-box
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coros-box
          
      - run: |
          cd coros-box
          yarn
          yarn start
          cd ../
          rm -rf ./coros-box
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":memo: update profile"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: Author <actions@github.com>
