name: Update gist with WakaTime stats

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"


jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Clone and run waka-box
      run: |-
        git clone https://github.com/journey-ad/waka-box-go.git
        cd waka-box-go && go build -o waka ./cmd/box/main.go
        mv ./waka ../ && cd .. && rm -rf waka-box-go/
    - name: Commit and push
      run: |-
        ./waka
        git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
        git diff
        git add README.md && git commit -m ":memo: update profile" || exit 0
        git pull && git push